### PR TITLE
Update brew formula for 1.0

### PR DESCRIPTION
**Pull request by mberhault**
```
$ wget https://binaries.cockroachdb.com/cockroach-v1.0.src.tgz
2017-05-10 09:30:26 (18.3 MB/s) - ‘cockroach-v1.0.src.tgz’ saved
[68753479/68753479]
$ sha2 cockroach-v1.0.src.tgz
SHA-256 (cockroach-v1.0.src.tgz) =
ca87b10eec688195e0df4f85431b019f2980ae4b511ee321f91f945315efeb76
SHA-384 (cockroach-v1.0.src.tgz) =
852945017c596e75fd48f6c528f39a347b47f86e20d7eb2d6d6e366047f9dd7492f794d5ee90153a21b7dec1bd59b29d
SHA-512 (cockroach-v1.0.src.tgz) =
d74ad9546908535f9a7ad4172a04a5f86f5ed22698bbb005aec7478a52632e0497a966b859fd68b40894eb7ee68bfa80dc4188d198f2f23725b9cadd50a55191
```

### CODE REVIEW

**Comment by benesch** [comment]
:tada:

We should switch over to the new procedure

```bash
def install                                                                                        
  system "make", "install", "prefix=#{prefix}"                                                     
end  
```

but doesn't have to be now.

**Comment by mberhault** [comment]
Done. Might as well.

**Comment by benesch** [comment]
Checking now!

**Comment by a-robinson** [comment]
How confident are we in the new procedure? Switching now seems a bit risky if we aren't very sure about it.

**Comment by mberhault** [comment]
Pretty confident, this was the goal of one of the PRs going into 1.0. It's also easy to test by having homebrew use a local checkout of the branch (except for my homebrew for some reason).

**Comment by benesch** [comment]
```
$ brew uninstall --force cockroach && brew install cockroach
==> Installing cockroach from cockroachdb/cockroach
==> Downloading https://binaries.cockroachdb.com/cockroach-v1.0.src.tgz
Already downloaded: /Users/benesch/Library/Caches/Homebrew/cockroach-1.0.tgz
==> make install prefix=/usr/local/Cellar/cockroach/1.0
==> Caveats
CockroachDB is a distributed database intended for multi-server deployments.
For local development only, this formula ships a launchd configuration to
start a single-node cluster that stores its data under:
  /usr/local/var/cockroach/
Instead of the default port of 8080, the node serves its admin UI at:
  http://localhost:26256

Do NOT use this cluster to store data you care about; it runs in insecure
mode and may expose data publicly in e.g. a DNS rebinding attack. To run
CockroachDB securely, please see:
  https://www.cockroachlabs.com/docs/secure-a-cluster.html

To have launchd start cockroachdb/cockroach/cockroach now and restart at login:
  brew services start cockroachdb/cockroach/cockroach
Or, if you don't want/need a background service you can just run:
  cockroach start --insecure
==> Summary
🍺  /usr/local/Cellar/cockroach/1.0: 5 files, 60.7MB, built in 2 minutes 7 seconds

$ cockroach version
Build Tag:    v1.0
Build Time:   2017/05/10 13:46:03
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.1-parallelbuilds
C Compiler:   4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)
Build SHA-1:  43aa1ed04cd817348921ac27e11e25725f634aa6
Build Type:   development
```

:beers:

**Pull request merged**
