### PR TITLE
Set brew version to v1.0.1

### PR DESCRIPTION
**Pull request by mberhault**

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by benesch** [comment]
Actually, @mberhault, any reason to keep this tap around now that we're pointing people to Homebrew proper? https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb

**Comment by mberhault** [comment]
oh, I did not know we were. Is that what's picked up with the basic `brew install cockroach`? If so, we can probably drop this one

**Comment by benesch** [comment]
Yep, that's right! Just accidentally submitted a PR upstream while trying to figure out the new `brew bump-formula-pr` invocation: https://github.com/Homebrew/homebrew-core/pull/13932

**Comment by mberhault** [comment]
ok. closing this then. Could you update the release docs?

**Comment by benesch** [comment]
You bet.

**Pull request closed without merging**
